FROM nvcr.io/nvidia/tritonserver:23.04-py3 as build

WORKDIR /app/tensorrt_llm
COPY tekit .

RUN python3 scripts/build_wheel.py

FROM nvcr.io/nvidia/tritonserver:23.04-py3

WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r requirements.txt --extra-index-url https://pypi.ngc.nvidia.com
COPY --from=build /app/tensorrt_llm/build/tensorrt_llm*.whl .
RUN pip3 install tensorrt_llm*.whl --extra-index-url https://pypi.ngc.nvidia.com \
    && rm tensorrt_llm*.whl
