FROM nvcr.io/nvidia/tritonserver:23.04-py3 as build

WORKDIR /app/tensorrt_llm
COPY tekit .

RUN bash scripts/build_wheel.sh

FROM nvcr.io/nvidia/tritonserver:23.04-py3

WORKDIR /app
RUN pip3 install regex fire tritonclient[all] --extra-index-url https://pypi.ngc.nvidia.com
COPY --from=build /app/tensorrt_llm/build/tensorrt_llm*.whl .
RUN pip3 install tensorrt_llm*.whl --extra-index-url https://pypi.ngc.nvidia.com \
    && rm tensorrt_llm*.whl
