FROM nvcr.io/nvidia/tritonserver:23.04-py3 as build

WORKDIR /app/tekit
COPY tekit .
RUN bash scripts/build_wheel.sh

FROM nvcr.io/nvidia/tritonserver:23.04-py3

WORKDIR /app
COPY --from=build /app/tekit/build/tekit*.whl .
RUN pip3 install tekit*.whl --extra-index-url https://pypi.ngc.nvidia.com \
    && rm tekit*.whl
