blank_issues_enabled: false
contact_links:
  - name: Bug report or feature request
    url: https://github.com/triton-inference-server/server/issues/new/choose
    about: Please report issues for all Triton Inference Server components in the server repository.
